# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'csrwindow.ui'
#
# Created: Fri Nov 14 15:02:40 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CSRWindow(object):
    def setupUi(self, CSRWindow):
        CSRWindow.setObjectName("CSRWindow")
        CSRWindow.resize(379, 332)
        self.verticalLayout = QtWidgets.QVBoxLayout(CSRWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lblDomain = QtWidgets.QLabel(CSRWindow)
        self.lblDomain.setObjectName("lblDomain")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblDomain)
        self.txtDomain = QtWidgets.QLineEdit(CSRWindow)
        self.txtDomain.setObjectName("txtDomain")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtDomain)
        self.lblCountry = QtWidgets.QLabel(CSRWindow)
        self.lblCountry.setObjectName("lblCountry")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblCountry)
        self.txtCountry = QtWidgets.QLineEdit(CSRWindow)
        self.txtCountry.setObjectName("txtCountry")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtCountry)
        self.lblStateProvince = QtWidgets.QLabel(CSRWindow)
        self.lblStateProvince.setObjectName("lblStateProvince")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblStateProvince)
        self.txtStateProvince = QtWidgets.QLineEdit(CSRWindow)
        self.txtStateProvince.setObjectName("txtStateProvince")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtStateProvince)
        self.lblLocality = QtWidgets.QLabel(CSRWindow)
        self.lblLocality.setObjectName("lblLocality")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblLocality)
        self.txtLocality = QtWidgets.QLineEdit(CSRWindow)
        self.txtLocality.setObjectName("txtLocality")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtLocality)
        self.lblOrganization = QtWidgets.QLabel(CSRWindow)
        self.lblOrganization.setObjectName("lblOrganization")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lblOrganization)
        self.txtOrganization = QtWidgets.QLineEdit(CSRWindow)
        self.txtOrganization.setObjectName("txtOrganization")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtOrganization)
        self.lblOrganizationUnit = QtWidgets.QLabel(CSRWindow)
        self.lblOrganizationUnit.setObjectName("lblOrganizationUnit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lblOrganizationUnit)
        self.txtOrganizationUnit = QtWidgets.QLineEdit(CSRWindow)
        self.txtOrganizationUnit.setObjectName("txtOrganizationUnit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txtOrganizationUnit)
        self.lblEmail = QtWidgets.QLabel(CSRWindow)
        self.lblEmail.setObjectName("lblEmail")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lblEmail)
        self.txtEmail = QtWidgets.QLineEdit(CSRWindow)
        self.txtEmail.setObjectName("txtEmail")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.txtEmail)
        self.verticalLayout.addLayout(self.formLayout)
        self.chkSign = QtWidgets.QCheckBox(CSRWindow)
        self.chkSign.setObjectName("chkSign")
        self.verticalLayout.addWidget(self.chkSign)
        self.groupSign = QtWidgets.QGroupBox(CSRWindow)
        self.groupSign.setEnabled(False)
        self.groupSign.setObjectName("groupSign")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupSign)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lblDays = QtWidgets.QLabel(self.groupSign)
        self.lblDays.setObjectName("lblDays")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblDays)
        self.spinDays = QtWidgets.QSpinBox(self.groupSign)
        self.spinDays.setMinimum(1)
        self.spinDays.setMaximum(100000)
        self.spinDays.setProperty("value", 30)
        self.spinDays.setObjectName("spinDays")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinDays)
        self.verticalLayout.addWidget(self.groupSign)
        self.lblHostKey = QtWidgets.QLabel(CSRWindow)
        self.lblHostKey.setObjectName("lblHostKey")
        self.verticalLayout.addWidget(self.lblHostKey)
        self.lblCSR = QtWidgets.QLabel(CSRWindow)
        self.lblCSR.setObjectName("lblCSR")
        self.verticalLayout.addWidget(self.lblCSR)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(236, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnGenerate = QtWidgets.QPushButton(CSRWindow)
        self.btnGenerate.setObjectName("btnGenerate")
        self.horizontalLayout.addWidget(self.btnGenerate)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lblDomain.setBuddy(self.txtDomain)
        self.lblCountry.setBuddy(self.txtCountry)
        self.lblStateProvince.setBuddy(self.txtStateProvince)
        self.lblLocality.setBuddy(self.txtLocality)
        self.lblOrganization.setBuddy(self.txtOrganization)
        self.lblOrganizationUnit.setBuddy(self.txtOrganizationUnit)
        self.lblEmail.setBuddy(self.txtEmail)

        self.retranslateUi(CSRWindow)
        self.chkSign.toggled['bool'].connect(self.groupSign.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(CSRWindow)
        CSRWindow.setTabOrder(self.txtDomain, self.txtCountry)
        CSRWindow.setTabOrder(self.txtCountry, self.txtStateProvince)
        CSRWindow.setTabOrder(self.txtStateProvince, self.txtLocality)
        CSRWindow.setTabOrder(self.txtLocality, self.txtOrganization)
        CSRWindow.setTabOrder(self.txtOrganization, self.txtOrganizationUnit)
        CSRWindow.setTabOrder(self.txtOrganizationUnit, self.txtEmail)
        CSRWindow.setTabOrder(self.txtEmail, self.chkSign)
        CSRWindow.setTabOrder(self.chkSign, self.spinDays)
        CSRWindow.setTabOrder(self.spinDays, self.btnGenerate)

    def retranslateUi(self, CSRWindow):
        _translate = QtCore.QCoreApplication.translate
        CSRWindow.setWindowTitle(_translate("CSRWindow", "CSR Assistant"))
        self.lblDomain.setText(_translate("CSRWindow", "Domain"))
        self.txtDomain.setText(_translate("CSRWindow", "www."))
        self.lblCountry.setText(_translate("CSRWindow", "Country"))
        self.txtCountry.setText(_translate("CSRWindow", "IT"))
        self.lblStateProvince.setText(_translate("CSRWindow", "State or Province"))
        self.lblLocality.setText(_translate("CSRWindow", "Locality"))
        self.lblOrganization.setText(_translate("CSRWindow", "Organization"))
        self.lblOrganizationUnit.setText(_translate("CSRWindow", "Organization Unit"))
        self.txtOrganizationUnit.setText(_translate("CSRWindow", "Web Department"))
        self.lblEmail.setText(_translate("CSRWindow", "Email"))
        self.chkSign.setText(_translate("CSRWindow", "Generate self-signed certificate"))
        self.groupSign.setTitle(_translate("CSRWindow", "Sign options"))
        self.lblDays.setText(_translate("CSRWindow", "Days of validation"))
        self.lblHostKey.setText(_translate("CSRWindow", "Private host key:"))
        self.lblCSR.setText(_translate("CSRWindow", "Certificate request:"))
        self.btnGenerate.setText(_translate("CSRWindow", "&Generate"))

