# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'csrassistant/csrwindow.ui'
#
# Created: Fri Jun 29 15:49:59 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_CSRWindow(object):
    def setupUi(self, CSRWindow):
        CSRWindow.setObjectName(_fromUtf8("CSRWindow"))
        CSRWindow.resize(379, 332)
        self.verticalLayout = QtGui.QVBoxLayout(CSRWindow)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lblDomain = QtGui.QLabel(CSRWindow)
        self.lblDomain.setObjectName(_fromUtf8("lblDomain"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblDomain)
        self.txtDomain = QtGui.QLineEdit(CSRWindow)
        self.txtDomain.setObjectName(_fromUtf8("txtDomain"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.txtDomain)
        self.lblCountry = QtGui.QLabel(CSRWindow)
        self.lblCountry.setObjectName(_fromUtf8("lblCountry"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblCountry)
        self.txtCountry = QtGui.QLineEdit(CSRWindow)
        self.txtCountry.setObjectName(_fromUtf8("txtCountry"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.txtCountry)
        self.lblStateProvince = QtGui.QLabel(CSRWindow)
        self.lblStateProvince.setObjectName(_fromUtf8("lblStateProvince"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblStateProvince)
        self.txtStateProvince = QtGui.QLineEdit(CSRWindow)
        self.txtStateProvince.setObjectName(_fromUtf8("txtStateProvince"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.txtStateProvince)
        self.lblLocality = QtGui.QLabel(CSRWindow)
        self.lblLocality.setObjectName(_fromUtf8("lblLocality"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lblLocality)
        self.txtLocality = QtGui.QLineEdit(CSRWindow)
        self.txtLocality.setObjectName(_fromUtf8("txtLocality"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.txtLocality)
        self.lblOrganization = QtGui.QLabel(CSRWindow)
        self.lblOrganization.setObjectName(_fromUtf8("lblOrganization"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.lblOrganization)
        self.txtOrganization = QtGui.QLineEdit(CSRWindow)
        self.txtOrganization.setObjectName(_fromUtf8("txtOrganization"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.txtOrganization)
        self.lblOrganizationUnit = QtGui.QLabel(CSRWindow)
        self.lblOrganizationUnit.setObjectName(_fromUtf8("lblOrganizationUnit"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.lblOrganizationUnit)
        self.txtOrganizationUnit = QtGui.QLineEdit(CSRWindow)
        self.txtOrganizationUnit.setObjectName(_fromUtf8("txtOrganizationUnit"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.txtOrganizationUnit)
        self.lblEmail = QtGui.QLabel(CSRWindow)
        self.lblEmail.setObjectName(_fromUtf8("lblEmail"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.lblEmail)
        self.txtEmail = QtGui.QLineEdit(CSRWindow)
        self.txtEmail.setObjectName(_fromUtf8("txtEmail"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.txtEmail)
        self.verticalLayout.addLayout(self.formLayout)
        self.chkSign = QtGui.QCheckBox(CSRWindow)
        self.chkSign.setObjectName(_fromUtf8("chkSign"))
        self.verticalLayout.addWidget(self.chkSign)
        self.groupSign = QtGui.QGroupBox(CSRWindow)
        self.groupSign.setEnabled(False)
        self.groupSign.setObjectName(_fromUtf8("groupSign"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupSign)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.lblDays = QtGui.QLabel(self.groupSign)
        self.lblDays.setObjectName(_fromUtf8("lblDays"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblDays)
        self.spinDays = QtGui.QSpinBox(self.groupSign)
        self.spinDays.setMinimum(1)
        self.spinDays.setMaximum(100000)
        self.spinDays.setProperty("value", 30)
        self.spinDays.setObjectName(_fromUtf8("spinDays"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinDays)
        self.verticalLayout.addWidget(self.groupSign)
        self.lblHostKey = QtGui.QLabel(CSRWindow)
        self.lblHostKey.setObjectName(_fromUtf8("lblHostKey"))
        self.verticalLayout.addWidget(self.lblHostKey)
        self.lblCSR = QtGui.QLabel(CSRWindow)
        self.lblCSR.setObjectName(_fromUtf8("lblCSR"))
        self.verticalLayout.addWidget(self.lblCSR)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(236, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnGenerate = QtGui.QPushButton(CSRWindow)
        self.btnGenerate.setObjectName(_fromUtf8("btnGenerate"))
        self.horizontalLayout.addWidget(self.btnGenerate)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lblDomain.setBuddy(self.txtDomain)
        self.lblCountry.setBuddy(self.txtCountry)
        self.lblStateProvince.setBuddy(self.txtStateProvince)
        self.lblLocality.setBuddy(self.txtLocality)
        self.lblOrganization.setBuddy(self.txtOrganization)
        self.lblOrganizationUnit.setBuddy(self.txtOrganizationUnit)
        self.lblEmail.setBuddy(self.txtEmail)

        self.retranslateUi(CSRWindow)
        QtCore.QObject.connect(self.chkSign, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.groupSign.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(CSRWindow)
        CSRWindow.setTabOrder(self.txtDomain, self.txtCountry)
        CSRWindow.setTabOrder(self.txtCountry, self.txtStateProvince)
        CSRWindow.setTabOrder(self.txtStateProvince, self.txtLocality)
        CSRWindow.setTabOrder(self.txtLocality, self.txtOrganization)
        CSRWindow.setTabOrder(self.txtOrganization, self.txtOrganizationUnit)
        CSRWindow.setTabOrder(self.txtOrganizationUnit, self.txtEmail)
        CSRWindow.setTabOrder(self.txtEmail, self.chkSign)
        CSRWindow.setTabOrder(self.chkSign, self.spinDays)
        CSRWindow.setTabOrder(self.spinDays, self.btnGenerate)

    def retranslateUi(self, CSRWindow):
        CSRWindow.setWindowTitle(QtGui.QApplication.translate("CSRWindow", "CSR Assistant", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDomain.setText(QtGui.QApplication.translate("CSRWindow", "Domain", None, QtGui.QApplication.UnicodeUTF8))
        self.txtDomain.setText(QtGui.QApplication.translate("CSRWindow", "www.", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCountry.setText(QtGui.QApplication.translate("CSRWindow", "Country", None, QtGui.QApplication.UnicodeUTF8))
        self.txtCountry.setText(QtGui.QApplication.translate("CSRWindow", "IT", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStateProvince.setText(QtGui.QApplication.translate("CSRWindow", "State or Province", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLocality.setText(QtGui.QApplication.translate("CSRWindow", "Locality", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOrganization.setText(QtGui.QApplication.translate("CSRWindow", "Organization", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOrganizationUnit.setText(QtGui.QApplication.translate("CSRWindow", "Organization Unit", None, QtGui.QApplication.UnicodeUTF8))
        self.txtOrganizationUnit.setText(QtGui.QApplication.translate("CSRWindow", "Web Department", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEmail.setText(QtGui.QApplication.translate("CSRWindow", "Email", None, QtGui.QApplication.UnicodeUTF8))
        self.chkSign.setText(QtGui.QApplication.translate("CSRWindow", "Generate self-signed certificate", None, QtGui.QApplication.UnicodeUTF8))
        self.groupSign.setTitle(QtGui.QApplication.translate("CSRWindow", "Sign options", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDays.setText(QtGui.QApplication.translate("CSRWindow", "Days of validation", None, QtGui.QApplication.UnicodeUTF8))
        self.lblHostKey.setText(QtGui.QApplication.translate("CSRWindow", "Private host key:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCSR.setText(QtGui.QApplication.translate("CSRWindow", "Certificate request:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnGenerate.setText(QtGui.QApplication.translate("CSRWindow", "&Generate", None, QtGui.QApplication.UnicodeUTF8))

