# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'csrwindow.ui'
#
# Created: Thu Sep  3 11:42:32 2009
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_CSRWindow(object):
    def setupUi(self, CSRWindow):
        CSRWindow.setObjectName("CSRWindow")
        CSRWindow.resize(352, 268)
        self.gridLayout = QtGui.QGridLayout(CSRWindow)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lblDomain = QtGui.QLabel(CSRWindow)
        self.lblDomain.setObjectName("lblDomain")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblDomain)
        self.txtDomain = QtGui.QLineEdit(CSRWindow)
        self.txtDomain.setObjectName("txtDomain")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.txtDomain)
        self.lblCountry = QtGui.QLabel(CSRWindow)
        self.lblCountry.setObjectName("lblCountry")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblCountry)
        self.txtCountry = QtGui.QLineEdit(CSRWindow)
        self.txtCountry.setObjectName("txtCountry")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.txtCountry)
        self.lblStateProvince = QtGui.QLabel(CSRWindow)
        self.lblStateProvince.setObjectName("lblStateProvince")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblStateProvince)
        self.txtStateProvince = QtGui.QLineEdit(CSRWindow)
        self.txtStateProvince.setObjectName("txtStateProvince")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.txtStateProvince)
        self.lblLocality = QtGui.QLabel(CSRWindow)
        self.lblLocality.setObjectName("lblLocality")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lblLocality)
        self.txtLocality = QtGui.QLineEdit(CSRWindow)
        self.txtLocality.setObjectName("txtLocality")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.txtLocality)
        self.lblOrganization = QtGui.QLabel(CSRWindow)
        self.lblOrganization.setObjectName("lblOrganization")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.lblOrganization)
        self.txtOrganization = QtGui.QLineEdit(CSRWindow)
        self.txtOrganization.setObjectName("txtOrganization")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.txtOrganization)
        self.txtOrganizationUnit = QtGui.QLineEdit(CSRWindow)
        self.txtOrganizationUnit.setObjectName("txtOrganizationUnit")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.txtOrganizationUnit)
        self.lblOrganizationUnit = QtGui.QLabel(CSRWindow)
        self.lblOrganizationUnit.setObjectName("lblOrganizationUnit")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.lblOrganizationUnit)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 2)
        self.lblHostKey = QtGui.QLabel(CSRWindow)
        self.lblHostKey.setObjectName("lblHostKey")
        self.gridLayout.addWidget(self.lblHostKey, 2, 0, 1, 2)
        self.lblCSR = QtGui.QLabel(CSRWindow)
        self.lblCSR.setObjectName("lblCSR")
        self.gridLayout.addWidget(self.lblCSR, 3, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(236, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.btnGenerate = QtGui.QPushButton(CSRWindow)
        self.btnGenerate.setObjectName("btnGenerate")
        self.gridLayout.addWidget(self.btnGenerate, 4, 1, 1, 1)
        self.chkSign = QtGui.QCheckBox(CSRWindow)
        self.chkSign.setObjectName("chkSign")
        self.gridLayout.addWidget(self.chkSign, 1, 0, 1, 1)
        self.lblDomain.setBuddy(self.txtDomain)
        self.lblCountry.setBuddy(self.txtCountry)
        self.lblStateProvince.setBuddy(self.txtStateProvince)
        self.lblLocality.setBuddy(self.txtLocality)
        self.lblOrganization.setBuddy(self.txtOrganization)
        self.lblOrganizationUnit.setBuddy(self.txtOrganizationUnit)

        self.retranslateUi(CSRWindow)
        QtCore.QMetaObject.connectSlotsByName(CSRWindow)

    def retranslateUi(self, CSRWindow):
        CSRWindow.setWindowTitle(QtGui.QApplication.translate("CSRWindow", "CSR Assistant", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDomain.setText(QtGui.QApplication.translate("CSRWindow", "Domain", None, QtGui.QApplication.UnicodeUTF8))
        self.txtDomain.setText(QtGui.QApplication.translate("CSRWindow", "www.", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCountry.setText(QtGui.QApplication.translate("CSRWindow", "Country", None, QtGui.QApplication.UnicodeUTF8))
        self.txtCountry.setText(QtGui.QApplication.translate("CSRWindow", "IT", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStateProvince.setText(QtGui.QApplication.translate("CSRWindow", "State or Province", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLocality.setText(QtGui.QApplication.translate("CSRWindow", "Locality", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOrganization.setText(QtGui.QApplication.translate("CSRWindow", "Organization", None, QtGui.QApplication.UnicodeUTF8))
        self.txtOrganizationUnit.setText(QtGui.QApplication.translate("CSRWindow", "Web Department", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOrganizationUnit.setText(QtGui.QApplication.translate("CSRWindow", "Organization Unit", None, QtGui.QApplication.UnicodeUTF8))
        self.lblHostKey.setText(QtGui.QApplication.translate("CSRWindow", "Private host key:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCSR.setText(QtGui.QApplication.translate("CSRWindow", "Certificate request:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnGenerate.setText(QtGui.QApplication.translate("CSRWindow", "&Generate", None, QtGui.QApplication.UnicodeUTF8))
        self.chkSign.setText(QtGui.QApplication.translate("CSRWindow", "Generate self-signed certificate", None, QtGui.QApplication.UnicodeUTF8))

